# This Nix expression builds a WordPress theme and a Composer project for the Caravan Club website.

{
  pkgs,
  nix-filter,
  lib,
  ...
}:

let
  php = pkgs.php84;

  nodeBuild = pkgs.buildNpmPackage {
    version = "1.0.0";
    name = "bedrock-wp-theme";
    src = ./.;

    __noChroot = false; # Allow or disallow build-step to operate outside sandbox

    buildPhase = ''
      rm -f .gitignore
      npm run build
    '';

    # Use terminal command `prefetch-npm-deps package-lock.json` to generate hash
    npmDepsHash = "sha256-W+YK9f0UbAHz59lvlX+dHAQ3Ri3KJZlHBd3u9IC9F8o=";
  };

  composerBuild = php.buildComposerProject {
    pname = "bedrock-wp"; # Project name.
    version = "1.0.0"; # Version of the project.
    nativeBuildInputs = with pkgs; [ rsync ]; # Native build inputs.
    src = ./.;
    __noChroot = false; # Allow or disallow build-step to operate outside sandbox
    composerStrictValidation = false; # Disable strict validation for Composer.
    composerNoPlugins = false;

    postInstall = ''
      # Define paths for project folders.
      PUBLIC_CONTENT=$out/share/php/bedrock-wp/web/app
      PLUGINS=$PUBLIC_CONTENT/plugins
      MU_PLUGINS=$PUBLIC_CONTENT/mu-plugins

      rm .gitignore

      mkdir -p "$MU_PLUGINS" "PUBLIC_CONTENT" "PLUGINS"

      # Sync to public to not have to rely on external symlinks generated by composer.
      cp -rL ${nodeBuild}/lib/node_modules/bedrock-base/web/app/* $PUBLIC_CONTENT
    '';

    # Run `nix build` and wait for the error
    # In the error response you'll se Nix complain about hash mismatch
    # Copy the "Got" has and paste below and run `nix build` again
    vendorHash = "sha256-QbSPJcFGxnlsXZGg5/O5VJyWUBFiWUh9A6YfWS/hCQg="; # Hash for Composer vendor directory.
  };
in
composerBuild
